main_project_outline: ../main.md
main_project_outline_wf: main.json
project_node_id: 359efefc-ac20-0a09-a571-2f208a1a61ae
wf_last_modified_at: 1769219728
patches_folder: patches/
applied_patches_index: applied_patches.yaml
